language: python

dist: precise

python:
  - "2.7"
  - "3.5"

install:
  - pip install -r requirements.txt
  
script:
  - py.test
  - pyinstaller --onefile --hidden-import tkinter.filedialog  ./src/obj2png.py 

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: dist/obj2png
  overwrite: true
  skip_cleanup: true
  on:
    tag: true

